debug: true
host: 0.0.0.0
port: 8080
db:
  - user: events
  - pass: changeme
  - host: db
  - port: 5432
  - name: events
broker:
  - user: guest
  - pass: guest
  - host: queue
  - port: 5672
  - exchange: events
  - queue: events
