---
version: '3.1'

services:
  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: events
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: events

  queue:
    image: rabbitmq:3.8-management-alpine
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
