global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1

scrape_configs:
  - job_name: postgres
    static_configs:
      - targets: ["postgres_exporter:9187"]
  - job_name: sender
    static_configs:
      - targets: ["calendar_sender:9187"]
  - job_name: calendar
    static_configs:
      - targets: ["calendar_api:9187"]

